name: tn-bustax2024-dev
channels:
- conda-forge
dependencies:
- python>=3.10,<3.12
- ipython
- jupyter
- numpy
- pandas>=1.4.4
- bokeh>=3.4.0
- matplotlib
- pip
- pip:
  - cost-of-capital-calculator
  - taxcalc
  - selenium
  - geopandas
  - openpyxl
